# Parameter set for
topic: /ouster_cloud_node/points
deskew: false
max_range: 100.0
min_range: 0.5
voxel_size: 0.2
max_points_per_voxelized_scan: 1800
min_points_per_voxelized_scan: 1500
planarity_threshold: 0.15
max_points_per_voxel: 1
initial_threshold: 2.0
min_motion_th: 0.1
max_num_iterations: 100
convergence_criterion: 0.0001

